CREATE TABLE IF NOT EXISTS event (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation VARCHAR (3000),
    category_id BIGINT NOT NULL ,
    description varchar(5000),
    event_date TIMESTAMP WITH TIME ZONE,
    lat DECIMAL (8,6) NOT NULL,
    lon DECIMAL (9,6) NOT NULL,
    paid BOOLEAN DEFAULT FALSE,
    participant_limit INTEGER,
    request_moderation BOOLEAN,
    title VARCHAR(250) NOT NULL,
    confirmed_request INTEGER,
    created_on TIMESTAMP WITHOUT TIME ZONE,
    initiator_id  BIGINT REFERENCES users (user_id) ON DELETE RESTRICT,
    published_on TIMESTAMP WITHOUT TIME ZONE,
    state VARCHAR(20),
    views BIGINT
);

CREATE TABLE IF NOT EXISTS users(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR (100),
    email VARCHAR(100)
--     CONSTRAINT uq_email UNIQUE (email)
);
CREATE TABLE IF NOT EXISTS participation (
    participation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP NOT NULL,
    event_id BIGINT REFERENCES event (event_id) ON DELETE RESTRICT,
    requester_id BIGINT REFERENCES users (user_id) ON DELETE RESTRICT,
    status VARCHAR(50)
);
CREATE TABLE IF NOT EXISTS category(
category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
category_name VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS compilation(
    compilation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN DEFAULT FALSE,
    tittle VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS event_compilations
(
    compilation_id BIGINT REFERENCES compilation (compilation_id) ON DELETE RESTRICT,
    event_id       BIGINT REFERENCES event (event_id) ON DELETE RESTRICT,
    PRIMARY KEY (compilation_id, event_id)
);
















-- DROP TABLE IF EXISTS users, categories, events, requests, compilations, event_compilations CASCADE ;
--
-- CREATE TABLE IF NOT EXISTS users (
--                                      user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--                                      email   VARCHAR(255) NOT NULL,
--                                      name    VARCHAR(255) NOT NULL,
--                                      CONSTRAINT uq_email UNIQUE (email)
-- );
--
-- CREATE TABLE IF NOT EXISTS categories (
--                                           category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--                                           name        VARCHAR(255) NOT NULL,
--                                           CONSTRAINT uq_category_name UNIQUE (name)
-- );
--
-- CREATE TABLE IF NOT EXISTS events (
--                                       event_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--                                       annotation         VARCHAR(2000) NOT NULL,
--                                       category_id        BIGINT REFERENCES categories (category_id) ON DELETE RESTRICT,
--                                       description        VARCHAR(7000) NOT NULL,
--                                       event_date         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
--                                       lat                REAL NOT NULL,
--                                       lon                REAL NOT NULL,
--                                       paid               BOOLEAN DEFAULT FALSE,
--                                       participant_limit  INTEGER DEFAULT 0,
--                                       request_moderation BOOLEAN DEFAULT TRUE,
--                                       title              VARCHAR(120) NOT NULL,
--                                       confirmed_requests INTEGER DEFAULT 0,
--                                       created_on         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
--                                       initiator          BIGINT REFERENCES users (user_id) ON DELETE RESTRICT,
--                                       published_on       TIMESTAMP WITHOUT TIME ZONE,
--                                       state              VARCHAR,
--                                       views              BIGINT DEFAULT 0
-- );
--
-- CREATE TABLE IF NOT EXISTS requests (
--                                         request_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--                                         created      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
--                                         event_id     BIGINT REFERENCES events (event_id) ON DELETE RESTRICT,
--                                         requester_id BIGINT REFERENCES users (user_id) ON DELETE RESTRICT,
--                                         status       VARCHAR,
--                                         CONSTRAINT uq_request UNIQUE (event_id, requester_id)
-- );
--
-- CREATE TABLE IF NOT EXISTS compilations (
--                                             compilation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--                                             pinned         BOOLEAN DEFAULT FALSE,
--                                             title          VARCHAR NOT NULL
-- );
--
-- CREATE TABLE IF NOT EXISTS event_compilations (
--                                                   compilation_id BIGINT REFERENCES compilations(compilation_id) ON DELETE RESTRICT,
--                                                   event_id BIGINT REFERENCES events(event_id) ON DELETE RESTRICT,
--                                                   PRIMARY KEY (compilation_id, event_id)
-- );